stages:
  - module-pipelines

kubernetes:
  stage: module-pipelines
  trigger:
    include:
      - "/kuber/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - kuber/**/*

helm:
  stage: module-pipelines
  trigger:
    include:
      - "/sausage-store-chart/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - sausage-store-chart/**/*
