---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-{{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {

      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }

      location /api {
          proxy_pass http://sausage-backend:{{ .Values.global.backendPort | int }};
      }
    }
