apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}-{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 20%
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - image: {{ .Values.global.imageRegistry }}/{{ .Values.imageName }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          name: "{{ .Values.name }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault-helm
                  key: vault_host
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-helm
                  key: vault_token
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: postgres_host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: postgres_port
            - name: POSTGRES_DBNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-helm
                  key: postgres_dbname
            - name: SPRING_DATASOURCE_URL
              value: "{{ .Values.global.springDatasourceUrl }}"
            - name: BACKEND_PORT
              value: {{ .Values.global.backend_port }}
            - name: SPRING_FLYWAY_BASELINE
              value: "{{ .Values.global.springFlywayBaseline }}"
          ports:
            - name: backend
              containerPort: {{ .Values.global.backendPort | int }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.global.backendPort | int }}
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 2
            failureThreshold: 6
      imagePullSecrets:
        - name: docker-config-secret-helm
