# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: c2F1c2FnZS1zdG9yZS10b2tlbg==
  vault_host: NTEuMjUwLjc4LjM2
type: Opaque

# Секрет, необходимый, чтобы соединяться с PostgresSQL
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
data:
  postgres_host: cmMxYi05ZW4xdXQ1a3JkYWNzdmM3Lm1kYi55YW5kZXhjbG91ZC5uZXQ=
  postgres_port: NjQzMg==
  postgres_dbname: Z29ybHltMjY5OQ==
type: Opaque
# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CgkJCSJhdXRoIjogIlpYSmhhMmh0WlhSNmVXRnViM1k2TlZrNWNESnlSM05RUVcxSFVIST0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson