---
apiVersion: v1
kind: Secret
metadata:
  name: vault-helm
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
data:
  vault_token: {{ .Values.secrets.vaultToken | b64enc }}
  vault_host: {{ .Values.secrets.vaultHost | b64enc }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-helm
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
data:
  postgres_host: {{ .Values.secrets.postgresHost | b64enc }}
  postgres_port: {{ .Values.secrets.postgresPort | toString | b64enc }}
  postgres_dbname: {{ .Values.secrets.postgresDBName | b64enc }}
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: docker-config-secret-helm
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "sausage-store.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.secrets.dockerConfigJson }}
type: kubernetes.io/dockerconfigjson
