---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
  labels:
    app: backend-report
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    # шаблон для создания Pod'ов
    spec:
      containers:
        - image: gitlab.praktikum-services.ru:5050/anton-alekseyev/sausage-store/sausage-backend-report:latest
          name: backend-report
          imagePullPolicy: IfNotPresent
          env:
            - name: VAULT_HOST
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_host
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: vault_token
          livenessProbe:
            # проверка живучести выполнит запрос HTTP GET
            httpGet:
              # путь к запросу в HTTP-запросе
              path: /actuator/health
              # порт, к которому должна подключиться проверка
              port: 8080
            # перед исполнением первой проверки подождать 15 секунд, пока стартанёт бэкенд
            initialDelaySeconds: 15
            # период выполнения проверки
            periodSeconds: 30
            # максимальное время выполнения проверки (по умолчанию 1 раз)
            timeoutSeconds: 2
            # сколько раз пробовать попытку, если она провалилась (по умолчанию 1 раз)
            failureThreshold: 6
      # чтобы кубер мог скачивать образы из нашего GitLab Registry
      imagePullSecrets:
        - name: docker-config-secret